# Generated by Django 5.0.2 on 2025-05-06 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.CreateModel(
            name="OpenSourceProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="opensource/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Développement Web"),
                            ("data", "Data Science"),
                            ("energy", "Énergétique"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Terminé"),
                            ("in_progress", "En cours"),
                            ("planned", "Planifié"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("github_link", models.URLField(blank=True, null=True)),
                ("drive_link", models.URLField(blank=True, null=True)),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projects", to="collaborative_projects.technology"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet Open Source",
                "verbose_name_plural": "Projets Open Source",
                "ordering": ["-date_created"],
            },
        ),
    ]
