# Generated by Django 5.0.2 on 2025-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborative_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opensourceproject",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="opensourceproject",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Développement Web"),
                    ("data", "Data Science"),
                    ("energy", "Énergétique"),
                    ("other", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opensourceproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Terminé"),
                    ("in_progress", "En cours"),
                    ("planned", "Planifié"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opensourceproject",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, to="collaborative_projects.technology"
            ),
        ),
    ]
