# Generated by Django 5.0.2 on 2025-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborative_projects", "0002_opensourceproject_views_count_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opensourceproject",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="opensource_projects", to="core.category"
            ),
        ),
    ]
