# Generated by Django 4.2.7 on 2023-12-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("contain", models.TextField()),
                ("slug", models.SlugField(max_length=100)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                ("theme", models.TextField(verbose_name=200)),
            ],
        ),
    ]
