# Generated by Django 5.0.2 on 2025-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_theme_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
