# Generated by Django 5.0.2 on 2025-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_category_comment_contact_article_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articles.category"
            ),
        ),
    ]
