# Generated by Django 5.0.2 on 2025-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_remove_article_category_article_categories"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="core.category"
            ),
        ),
    ]
