# Generated by Django 5.0.2 on 2025-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_alter_comment_options_comment_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Titre de l'image", max_length=100),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image du carrousel", upload_to="carousel/"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Afficher cette image dans le carrousel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image du carrousel",
                "verbose_name_plural": "Images du carrousel",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
