# Generated by Django 5.0.2 on 2025-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.category"
            ),
        ),
    ]
