# Generated by Django 5.0.2 on 2025-05-07 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
    ]
